// Generated by gencpp from file pad_msgs/ClientResponseResponse.msg
// DO NOT EDIT!


#ifndef PAD_MSGS_MESSAGE_CLIENTRESPONSERESPONSE_H
#define PAD_MSGS_MESSAGE_CLIENTRESPONSERESPONSE_H


#include <string>
#include <vector>
#include <map>

#include <ros/types.h>
#include <ros/serialization.h>
#include <ros/builtin_message_traits.h>
#include <ros/message_operations.h>


namespace pad_msgs
{
template <class ContainerAllocator>
struct ClientResponseResponse_
{
  typedef ClientResponseResponse_<ContainerAllocator> Type;

  ClientResponseResponse_()
    : clientResponse(0)  {
    }
  ClientResponseResponse_(const ContainerAllocator& _alloc)
    : clientResponse(0)  {
  (void)_alloc;
    }



   typedef uint8_t _clientResponse_type;
  _clientResponse_type clientResponse;





  typedef boost::shared_ptr< ::pad_msgs::ClientResponseResponse_<ContainerAllocator> > Ptr;
  typedef boost::shared_ptr< ::pad_msgs::ClientResponseResponse_<ContainerAllocator> const> ConstPtr;

}; // struct ClientResponseResponse_

typedef ::pad_msgs::ClientResponseResponse_<std::allocator<void> > ClientResponseResponse;

typedef boost::shared_ptr< ::pad_msgs::ClientResponseResponse > ClientResponseResponsePtr;
typedef boost::shared_ptr< ::pad_msgs::ClientResponseResponse const> ClientResponseResponseConstPtr;

// constants requiring out of line definition



template<typename ContainerAllocator>
std::ostream& operator<<(std::ostream& s, const ::pad_msgs::ClientResponseResponse_<ContainerAllocator> & v)
{
ros::message_operations::Printer< ::pad_msgs::ClientResponseResponse_<ContainerAllocator> >::stream(s, "", v);
return s;
}


template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator==(const ::pad_msgs::ClientResponseResponse_<ContainerAllocator1> & lhs, const ::pad_msgs::ClientResponseResponse_<ContainerAllocator2> & rhs)
{
  return lhs.clientResponse == rhs.clientResponse;
}

template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator!=(const ::pad_msgs::ClientResponseResponse_<ContainerAllocator1> & lhs, const ::pad_msgs::ClientResponseResponse_<ContainerAllocator2> & rhs)
{
  return !(lhs == rhs);
}


} // namespace pad_msgs

namespace ros
{
namespace message_traits
{





template <class ContainerAllocator>
struct IsFixedSize< ::pad_msgs::ClientResponseResponse_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::pad_msgs::ClientResponseResponse_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::pad_msgs::ClientResponseResponse_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::pad_msgs::ClientResponseResponse_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct HasHeader< ::pad_msgs::ClientResponseResponse_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct HasHeader< ::pad_msgs::ClientResponseResponse_<ContainerAllocator> const>
  : FalseType
  { };


template<class ContainerAllocator>
struct MD5Sum< ::pad_msgs::ClientResponseResponse_<ContainerAllocator> >
{
  static const char* value()
  {
    return "cb3d6a26c15df5cc0e2a4cf9e7a416cb";
  }

  static const char* value(const ::pad_msgs::ClientResponseResponse_<ContainerAllocator>&) { return value(); }
  static const uint64_t static_value1 = 0xcb3d6a26c15df5ccULL;
  static const uint64_t static_value2 = 0x0e2a4cf9e7a416cbULL;
};

template<class ContainerAllocator>
struct DataType< ::pad_msgs::ClientResponseResponse_<ContainerAllocator> >
{
  static const char* value()
  {
    return "pad_msgs/ClientResponseResponse";
  }

  static const char* value(const ::pad_msgs::ClientResponseResponse_<ContainerAllocator>&) { return value(); }
};

template<class ContainerAllocator>
struct Definition< ::pad_msgs::ClientResponseResponse_<ContainerAllocator> >
{
  static const char* value()
  {
    return "uint8 clientResponse # Indice dell'opzione scelta\n"
;
  }

  static const char* value(const ::pad_msgs::ClientResponseResponse_<ContainerAllocator>&) { return value(); }
};

} // namespace message_traits
} // namespace ros

namespace ros
{
namespace serialization
{

  template<class ContainerAllocator> struct Serializer< ::pad_msgs::ClientResponseResponse_<ContainerAllocator> >
  {
    template<typename Stream, typename T> inline static void allInOne(Stream& stream, T m)
    {
      stream.next(m.clientResponse);
    }

    ROS_DECLARE_ALLINONE_SERIALIZER
  }; // struct ClientResponseResponse_

} // namespace serialization
} // namespace ros

namespace ros
{
namespace message_operations
{

template<class ContainerAllocator>
struct Printer< ::pad_msgs::ClientResponseResponse_<ContainerAllocator> >
{
  template<typename Stream> static void stream(Stream& s, const std::string& indent, const ::pad_msgs::ClientResponseResponse_<ContainerAllocator>& v)
  {
    s << indent << "clientResponse: ";
    Printer<uint8_t>::stream(s, indent + "  ", v.clientResponse);
  }
};

} // namespace message_operations
} // namespace ros

#endif // PAD_MSGS_MESSAGE_CLIENTRESPONSERESPONSE_H
