// Generated by gencpp from file pad_msgs/ClientResponse.msg
// DO NOT EDIT!


#ifndef PAD_MSGS_MESSAGE_CLIENTRESPONSE_H
#define PAD_MSGS_MESSAGE_CLIENTRESPONSE_H

#include <ros/service_traits.h>


#include <pad_msgs/ClientResponseRequest.h>
#include <pad_msgs/ClientResponseResponse.h>


namespace pad_msgs
{

struct ClientResponse
{

typedef ClientResponseRequest Request;
typedef ClientResponseResponse Response;
Request request;
Response response;

typedef Request RequestType;
typedef Response ResponseType;

}; // struct ClientResponse
} // namespace pad_msgs


namespace ros
{
namespace service_traits
{


template<>
struct MD5Sum< ::pad_msgs::ClientResponse > {
  static const char* value()
  {
    return "cb3d6a26c15df5cc0e2a4cf9e7a416cb";
  }

  static const char* value(const ::pad_msgs::ClientResponse&) { return value(); }
};

template<>
struct DataType< ::pad_msgs::ClientResponse > {
  static const char* value()
  {
    return "pad_msgs/ClientResponse";
  }

  static const char* value(const ::pad_msgs::ClientResponse&) { return value(); }
};


// service_traits::MD5Sum< ::pad_msgs::ClientResponseRequest> should match
// service_traits::MD5Sum< ::pad_msgs::ClientResponse >
template<>
struct MD5Sum< ::pad_msgs::ClientResponseRequest>
{
  static const char* value()
  {
    return MD5Sum< ::pad_msgs::ClientResponse >::value();
  }
  static const char* value(const ::pad_msgs::ClientResponseRequest&)
  {
    return value();
  }
};

// service_traits::DataType< ::pad_msgs::ClientResponseRequest> should match
// service_traits::DataType< ::pad_msgs::ClientResponse >
template<>
struct DataType< ::pad_msgs::ClientResponseRequest>
{
  static const char* value()
  {
    return DataType< ::pad_msgs::ClientResponse >::value();
  }
  static const char* value(const ::pad_msgs::ClientResponseRequest&)
  {
    return value();
  }
};

// service_traits::MD5Sum< ::pad_msgs::ClientResponseResponse> should match
// service_traits::MD5Sum< ::pad_msgs::ClientResponse >
template<>
struct MD5Sum< ::pad_msgs::ClientResponseResponse>
{
  static const char* value()
  {
    return MD5Sum< ::pad_msgs::ClientResponse >::value();
  }
  static const char* value(const ::pad_msgs::ClientResponseResponse&)
  {
    return value();
  }
};

// service_traits::DataType< ::pad_msgs::ClientResponseResponse> should match
// service_traits::DataType< ::pad_msgs::ClientResponse >
template<>
struct DataType< ::pad_msgs::ClientResponseResponse>
{
  static const char* value()
  {
    return DataType< ::pad_msgs::ClientResponse >::value();
  }
  static const char* value(const ::pad_msgs::ClientResponseResponse&)
  {
    return value();
  }
};

} // namespace service_traits
} // namespace ros

#endif // PAD_MSGS_MESSAGE_CLIENTRESPONSE_H
