// Generated by gencpp from file pad_msgs/ClientResponseRequest.msg
// DO NOT EDIT!


#ifndef PAD_MSGS_MESSAGE_CLIENTRESPONSEREQUEST_H
#define PAD_MSGS_MESSAGE_CLIENTRESPONSEREQUEST_H


#include <string>
#include <vector>
#include <map>

#include <ros/types.h>
#include <ros/serialization.h>
#include <ros/builtin_message_traits.h>
#include <ros/message_operations.h>


namespace pad_msgs
{
template <class ContainerAllocator>
struct ClientResponseRequest_
{
  typedef ClientResponseRequest_<ContainerAllocator> Type;

  ClientResponseRequest_()
    {
    }
  ClientResponseRequest_(const ContainerAllocator& _alloc)
    {
  (void)_alloc;
    }







  typedef boost::shared_ptr< ::pad_msgs::ClientResponseRequest_<ContainerAllocator> > Ptr;
  typedef boost::shared_ptr< ::pad_msgs::ClientResponseRequest_<ContainerAllocator> const> ConstPtr;

}; // struct ClientResponseRequest_

typedef ::pad_msgs::ClientResponseRequest_<std::allocator<void> > ClientResponseRequest;

typedef boost::shared_ptr< ::pad_msgs::ClientResponseRequest > ClientResponseRequestPtr;
typedef boost::shared_ptr< ::pad_msgs::ClientResponseRequest const> ClientResponseRequestConstPtr;

// constants requiring out of line definition



template<typename ContainerAllocator>
std::ostream& operator<<(std::ostream& s, const ::pad_msgs::ClientResponseRequest_<ContainerAllocator> & v)
{
ros::message_operations::Printer< ::pad_msgs::ClientResponseRequest_<ContainerAllocator> >::stream(s, "", v);
return s;
}


} // namespace pad_msgs

namespace ros
{
namespace message_traits
{





template <class ContainerAllocator>
struct IsFixedSize< ::pad_msgs::ClientResponseRequest_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::pad_msgs::ClientResponseRequest_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::pad_msgs::ClientResponseRequest_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::pad_msgs::ClientResponseRequest_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct HasHeader< ::pad_msgs::ClientResponseRequest_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct HasHeader< ::pad_msgs::ClientResponseRequest_<ContainerAllocator> const>
  : FalseType
  { };


template<class ContainerAllocator>
struct MD5Sum< ::pad_msgs::ClientResponseRequest_<ContainerAllocator> >
{
  static const char* value()
  {
    return "d41d8cd98f00b204e9800998ecf8427e";
  }

  static const char* value(const ::pad_msgs::ClientResponseRequest_<ContainerAllocator>&) { return value(); }
  static const uint64_t static_value1 = 0xd41d8cd98f00b204ULL;
  static const uint64_t static_value2 = 0xe9800998ecf8427eULL;
};

template<class ContainerAllocator>
struct DataType< ::pad_msgs::ClientResponseRequest_<ContainerAllocator> >
{
  static const char* value()
  {
    return "pad_msgs/ClientResponseRequest";
  }

  static const char* value(const ::pad_msgs::ClientResponseRequest_<ContainerAllocator>&) { return value(); }
};

template<class ContainerAllocator>
struct Definition< ::pad_msgs::ClientResponseRequest_<ContainerAllocator> >
{
  static const char* value()
  {
    return "\n"
;
  }

  static const char* value(const ::pad_msgs::ClientResponseRequest_<ContainerAllocator>&) { return value(); }
};

} // namespace message_traits
} // namespace ros

namespace ros
{
namespace serialization
{

  template<class ContainerAllocator> struct Serializer< ::pad_msgs::ClientResponseRequest_<ContainerAllocator> >
  {
    template<typename Stream, typename T> inline static void allInOne(Stream&, T)
    {}

    ROS_DECLARE_ALLINONE_SERIALIZER
  }; // struct ClientResponseRequest_

} // namespace serialization
} // namespace ros

namespace ros
{
namespace message_operations
{

template<class ContainerAllocator>
struct Printer< ::pad_msgs::ClientResponseRequest_<ContainerAllocator> >
{
  template<typename Stream> static void stream(Stream&, const std::string&, const ::pad_msgs::ClientResponseRequest_<ContainerAllocator>&)
  {}
};

} // namespace message_operations
} // namespace ros

#endif // PAD_MSGS_MESSAGE_CLIENTRESPONSEREQUEST_H
