// Generated by gencpp from file pad_msgs/ServerMenuResponse.msg
// DO NOT EDIT!


#ifndef PAD_MSGS_MESSAGE_SERVERMENURESPONSE_H
#define PAD_MSGS_MESSAGE_SERVERMENURESPONSE_H


#include <string>
#include <vector>
#include <map>

#include <ros/types.h>
#include <ros/serialization.h>
#include <ros/builtin_message_traits.h>
#include <ros/message_operations.h>


namespace pad_msgs
{
template <class ContainerAllocator>
struct ServerMenuResponse_
{
  typedef ServerMenuResponse_<ContainerAllocator> Type;

  ServerMenuResponse_()
    : serverRes()
    , warning(0)  {
    }
  ServerMenuResponse_(const ContainerAllocator& _alloc)
    : serverRes(_alloc)
    , warning(0)  {
  (void)_alloc;
    }



   typedef std::basic_string<char, std::char_traits<char>, typename ContainerAllocator::template rebind<char>::other >  _serverRes_type;
  _serverRes_type serverRes;

   typedef int32_t _warning_type;
  _warning_type warning;





  typedef boost::shared_ptr< ::pad_msgs::ServerMenuResponse_<ContainerAllocator> > Ptr;
  typedef boost::shared_ptr< ::pad_msgs::ServerMenuResponse_<ContainerAllocator> const> ConstPtr;

}; // struct ServerMenuResponse_

typedef ::pad_msgs::ServerMenuResponse_<std::allocator<void> > ServerMenuResponse;

typedef boost::shared_ptr< ::pad_msgs::ServerMenuResponse > ServerMenuResponsePtr;
typedef boost::shared_ptr< ::pad_msgs::ServerMenuResponse const> ServerMenuResponseConstPtr;

// constants requiring out of line definition



template<typename ContainerAllocator>
std::ostream& operator<<(std::ostream& s, const ::pad_msgs::ServerMenuResponse_<ContainerAllocator> & v)
{
ros::message_operations::Printer< ::pad_msgs::ServerMenuResponse_<ContainerAllocator> >::stream(s, "", v);
return s;
}


template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator==(const ::pad_msgs::ServerMenuResponse_<ContainerAllocator1> & lhs, const ::pad_msgs::ServerMenuResponse_<ContainerAllocator2> & rhs)
{
  return lhs.serverRes == rhs.serverRes &&
    lhs.warning == rhs.warning;
}

template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator!=(const ::pad_msgs::ServerMenuResponse_<ContainerAllocator1> & lhs, const ::pad_msgs::ServerMenuResponse_<ContainerAllocator2> & rhs)
{
  return !(lhs == rhs);
}


} // namespace pad_msgs

namespace ros
{
namespace message_traits
{





template <class ContainerAllocator>
struct IsFixedSize< ::pad_msgs::ServerMenuResponse_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::pad_msgs::ServerMenuResponse_<ContainerAllocator> const>
  : FalseType
  { };

template <class ContainerAllocator>
struct IsMessage< ::pad_msgs::ServerMenuResponse_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::pad_msgs::ServerMenuResponse_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct HasHeader< ::pad_msgs::ServerMenuResponse_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct HasHeader< ::pad_msgs::ServerMenuResponse_<ContainerAllocator> const>
  : FalseType
  { };


template<class ContainerAllocator>
struct MD5Sum< ::pad_msgs::ServerMenuResponse_<ContainerAllocator> >
{
  static const char* value()
  {
    return "ff7d364c458f89755b0b214d0566cc8a";
  }

  static const char* value(const ::pad_msgs::ServerMenuResponse_<ContainerAllocator>&) { return value(); }
  static const uint64_t static_value1 = 0xff7d364c458f8975ULL;
  static const uint64_t static_value2 = 0x5b0b214d0566cc8aULL;
};

template<class ContainerAllocator>
struct DataType< ::pad_msgs::ServerMenuResponse_<ContainerAllocator> >
{
  static const char* value()
  {
    return "pad_msgs/ServerMenuResponse";
  }

  static const char* value(const ::pad_msgs::ServerMenuResponse_<ContainerAllocator>&) { return value(); }
};

template<class ContainerAllocator>
struct Definition< ::pad_msgs::ServerMenuResponse_<ContainerAllocator> >
{
  static const char* value()
  {
    return "string serverRes\n"
"int32 warning \n"
"\n"
;
  }

  static const char* value(const ::pad_msgs::ServerMenuResponse_<ContainerAllocator>&) { return value(); }
};

} // namespace message_traits
} // namespace ros

namespace ros
{
namespace serialization
{

  template<class ContainerAllocator> struct Serializer< ::pad_msgs::ServerMenuResponse_<ContainerAllocator> >
  {
    template<typename Stream, typename T> inline static void allInOne(Stream& stream, T m)
    {
      stream.next(m.serverRes);
      stream.next(m.warning);
    }

    ROS_DECLARE_ALLINONE_SERIALIZER
  }; // struct ServerMenuResponse_

} // namespace serialization
} // namespace ros

namespace ros
{
namespace message_operations
{

template<class ContainerAllocator>
struct Printer< ::pad_msgs::ServerMenuResponse_<ContainerAllocator> >
{
  template<typename Stream> static void stream(Stream& s, const std::string& indent, const ::pad_msgs::ServerMenuResponse_<ContainerAllocator>& v)
  {
    s << indent << "serverRes: ";
    Printer<std::basic_string<char, std::char_traits<char>, typename ContainerAllocator::template rebind<char>::other > >::stream(s, indent + "  ", v.serverRes);
    s << indent << "warning: ";
    Printer<int32_t>::stream(s, indent + "  ", v.warning);
  }
};

} // namespace message_operations
} // namespace ros

#endif // PAD_MSGS_MESSAGE_SERVERMENURESPONSE_H
