// Generated by gencpp from file pad_msgs/ServerMenu.msg
// DO NOT EDIT!


#ifndef PAD_MSGS_MESSAGE_SERVERMENU_H
#define PAD_MSGS_MESSAGE_SERVERMENU_H

#include <ros/service_traits.h>


#include <pad_msgs/ServerMenuRequest.h>
#include <pad_msgs/ServerMenuResponse.h>


namespace pad_msgs
{

struct ServerMenu
{

typedef ServerMenuRequest Request;
typedef ServerMenuResponse Response;
Request request;
Response response;

typedef Request RequestType;
typedef Response ResponseType;

}; // struct ServerMenu
} // namespace pad_msgs


namespace ros
{
namespace service_traits
{


template<>
struct MD5Sum< ::pad_msgs::ServerMenu > {
  static const char* value()
  {
    return "32596eb33160ebf8976ecc13590aa29c";
  }

  static const char* value(const ::pad_msgs::ServerMenu&) { return value(); }
};

template<>
struct DataType< ::pad_msgs::ServerMenu > {
  static const char* value()
  {
    return "pad_msgs/ServerMenu";
  }

  static const char* value(const ::pad_msgs::ServerMenu&) { return value(); }
};


// service_traits::MD5Sum< ::pad_msgs::ServerMenuRequest> should match
// service_traits::MD5Sum< ::pad_msgs::ServerMenu >
template<>
struct MD5Sum< ::pad_msgs::ServerMenuRequest>
{
  static const char* value()
  {
    return MD5Sum< ::pad_msgs::ServerMenu >::value();
  }
  static const char* value(const ::pad_msgs::ServerMenuRequest&)
  {
    return value();
  }
};

// service_traits::DataType< ::pad_msgs::ServerMenuRequest> should match
// service_traits::DataType< ::pad_msgs::ServerMenu >
template<>
struct DataType< ::pad_msgs::ServerMenuRequest>
{
  static const char* value()
  {
    return DataType< ::pad_msgs::ServerMenu >::value();
  }
  static const char* value(const ::pad_msgs::ServerMenuRequest&)
  {
    return value();
  }
};

// service_traits::MD5Sum< ::pad_msgs::ServerMenuResponse> should match
// service_traits::MD5Sum< ::pad_msgs::ServerMenu >
template<>
struct MD5Sum< ::pad_msgs::ServerMenuResponse>
{
  static const char* value()
  {
    return MD5Sum< ::pad_msgs::ServerMenu >::value();
  }
  static const char* value(const ::pad_msgs::ServerMenuResponse&)
  {
    return value();
  }
};

// service_traits::DataType< ::pad_msgs::ServerMenuResponse> should match
// service_traits::DataType< ::pad_msgs::ServerMenu >
template<>
struct DataType< ::pad_msgs::ServerMenuResponse>
{
  static const char* value()
  {
    return DataType< ::pad_msgs::ServerMenu >::value();
  }
  static const char* value(const ::pad_msgs::ServerMenuResponse&)
  {
    return value();
  }
};

} // namespace service_traits
} // namespace ros

#endif // PAD_MSGS_MESSAGE_SERVERMENU_H
