// Generated by gencpp from file pad_msgs/ServerMenuRequest.msg
// DO NOT EDIT!


#ifndef PAD_MSGS_MESSAGE_SERVERMENUREQUEST_H
#define PAD_MSGS_MESSAGE_SERVERMENUREQUEST_H


#include <string>
#include <vector>
#include <map>

#include <ros/types.h>
#include <ros/serialization.h>
#include <ros/builtin_message_traits.h>
#include <ros/message_operations.h>


namespace pad_msgs
{
template <class ContainerAllocator>
struct ServerMenuRequest_
{
  typedef ServerMenuRequest_<ContainerAllocator> Type;

  ServerMenuRequest_()
    : clientReq(0)  {
    }
  ServerMenuRequest_(const ContainerAllocator& _alloc)
    : clientReq(0)  {
  (void)_alloc;
    }



   typedef uint8_t _clientReq_type;
  _clientReq_type clientReq;





  typedef boost::shared_ptr< ::pad_msgs::ServerMenuRequest_<ContainerAllocator> > Ptr;
  typedef boost::shared_ptr< ::pad_msgs::ServerMenuRequest_<ContainerAllocator> const> ConstPtr;

}; // struct ServerMenuRequest_

typedef ::pad_msgs::ServerMenuRequest_<std::allocator<void> > ServerMenuRequest;

typedef boost::shared_ptr< ::pad_msgs::ServerMenuRequest > ServerMenuRequestPtr;
typedef boost::shared_ptr< ::pad_msgs::ServerMenuRequest const> ServerMenuRequestConstPtr;

// constants requiring out of line definition



template<typename ContainerAllocator>
std::ostream& operator<<(std::ostream& s, const ::pad_msgs::ServerMenuRequest_<ContainerAllocator> & v)
{
ros::message_operations::Printer< ::pad_msgs::ServerMenuRequest_<ContainerAllocator> >::stream(s, "", v);
return s;
}


template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator==(const ::pad_msgs::ServerMenuRequest_<ContainerAllocator1> & lhs, const ::pad_msgs::ServerMenuRequest_<ContainerAllocator2> & rhs)
{
  return lhs.clientReq == rhs.clientReq;
}

template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator!=(const ::pad_msgs::ServerMenuRequest_<ContainerAllocator1> & lhs, const ::pad_msgs::ServerMenuRequest_<ContainerAllocator2> & rhs)
{
  return !(lhs == rhs);
}


} // namespace pad_msgs

namespace ros
{
namespace message_traits
{





template <class ContainerAllocator>
struct IsFixedSize< ::pad_msgs::ServerMenuRequest_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::pad_msgs::ServerMenuRequest_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::pad_msgs::ServerMenuRequest_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::pad_msgs::ServerMenuRequest_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct HasHeader< ::pad_msgs::ServerMenuRequest_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct HasHeader< ::pad_msgs::ServerMenuRequest_<ContainerAllocator> const>
  : FalseType
  { };


template<class ContainerAllocator>
struct MD5Sum< ::pad_msgs::ServerMenuRequest_<ContainerAllocator> >
{
  static const char* value()
  {
    return "b8251afa4652503387afda47e4bbcf26";
  }

  static const char* value(const ::pad_msgs::ServerMenuRequest_<ContainerAllocator>&) { return value(); }
  static const uint64_t static_value1 = 0xb8251afa46525033ULL;
  static const uint64_t static_value2 = 0x87afda47e4bbcf26ULL;
};

template<class ContainerAllocator>
struct DataType< ::pad_msgs::ServerMenuRequest_<ContainerAllocator> >
{
  static const char* value()
  {
    return "pad_msgs/ServerMenuRequest";
  }

  static const char* value(const ::pad_msgs::ServerMenuRequest_<ContainerAllocator>&) { return value(); }
};

template<class ContainerAllocator>
struct Definition< ::pad_msgs::ServerMenuRequest_<ContainerAllocator> >
{
  static const char* value()
  {
    return "uint8 clientReq\n"
;
  }

  static const char* value(const ::pad_msgs::ServerMenuRequest_<ContainerAllocator>&) { return value(); }
};

} // namespace message_traits
} // namespace ros

namespace ros
{
namespace serialization
{

  template<class ContainerAllocator> struct Serializer< ::pad_msgs::ServerMenuRequest_<ContainerAllocator> >
  {
    template<typename Stream, typename T> inline static void allInOne(Stream& stream, T m)
    {
      stream.next(m.clientReq);
    }

    ROS_DECLARE_ALLINONE_SERIALIZER
  }; // struct ServerMenuRequest_

} // namespace serialization
} // namespace ros

namespace ros
{
namespace message_operations
{

template<class ContainerAllocator>
struct Printer< ::pad_msgs::ServerMenuRequest_<ContainerAllocator> >
{
  template<typename Stream> static void stream(Stream& s, const std::string& indent, const ::pad_msgs::ServerMenuRequest_<ContainerAllocator>& v)
  {
    s << indent << "clientReq: ";
    Printer<uint8_t>::stream(s, indent + "  ", v.clientReq);
  }
};

} // namespace message_operations
} // namespace ros

#endif // PAD_MSGS_MESSAGE_SERVERMENUREQUEST_H
